{{- if and $.Values.solidityVerificationTool.pvc.enabled $.Values.solidityVerificationTool.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: subscan-solidity-verification-tool
spec:
    storageClassName: {{ $.Values.solidityVerificationTool.pvc.storageClass }}
    accessModes:
        - {{ $.Values.solidityVerificationTool.pvc.accessMode }}
    resources:
        requests:
            storage: {{ $.Values.solidityVerificationTool.pvc.size }}
{{- end }}